### ISSUE TITLE
Fix RTD build

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsynphot_refactor#38]
For example: https://readthedocs.org/projects/stsynphot/builds/6141688/
```
Running Sphinx v1.5.3
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/stsynphot/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stsynphot/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stsynphot/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 134, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stsynphot/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "conf.py", line 42, in <module>
    from astropy_helpers.sphinx.conf import *
ImportError: No module named 'astropy_helpers.sphinx'

Exception occurred:
  File "conf.py", line 42, in <module>
    from astropy_helpers.sphinx.conf import *
ImportError: No module named 'astropy_helpers.sphinx'
```

**Comment by pllim** [comment]
Fixed.
