### ISSUE TITLE
Cannot load GALEX filter transmission curves

### ISSUE THREAD

**Issue by brentmsmith** [spacetelescope/stsynphot_refactor#70]
##### System information (version)
- stsynphot => 0.1.1
- Operating System / Platform => OS X 10.12.6
- Python => 3.7.3 [Clang 9.0.0 (clang-900.0.39.2)] on darwin

##### Detailed description

Cannot load GALEX filter transmission curves, throws error:

<details>

```bash
WARNING: No graph tables found; functionality will be SEVERELY crippled. [stsynphot.stio]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/stsynphot/spectrum.py", line 547, in band
    return ObservationSpectralElement.from_obsmode(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/stsynphot/spectrum.py", line 530, in from_obsmode
    component_dict=component_dict)
  File "/usr/local/lib/python3.7/site-packages/stsynphot/observationmode.py", line 372, in __init__
    obsmode, graphtable=graphtable, comptable=comptable)
  File "/usr/local/lib/python3.7/site-packages/stsynphot/observationmode.py", line 259, in __init__
    gt, self.gtname, self.primary_area = _process_graphtable(graphtable)
  File "/usr/local/lib/python3.7/site-packages/stsynphot/observationmode.py", line 159, in _process_graphtable
    gt = GraphTable(gtname)
  File "/usr/local/lib/python3.7/site-packages/stsynphot/tables.py", line 62, in __init__
    tab_ext=ext)
  File "/usr/local/lib/python3.7/site-packages/stsynphot/stio.py", line 305, in read_graphtable
    data = _read_table(filename, tab_ext, graph_dtypes)
  File "/usr/local/lib/python3.7/site-packages/stsynphot/stio.py", line 248, in _read_table
    data = ascii.read(filename, converters=converters)
  File "/usr/local/lib/python3.7/site-packages/astropy/io/ascii/ui.py", line 373, in read
    dat = _guess(table, new_kwargs, format, fast_reader)
  File "/usr/local/lib/python3.7/site-packages/astropy/io/ascii/ui.py", line 530, in _guess
    dat = reader.read(table)
  File "/usr/local/lib/python3.7/site-packages/astropy/io/ascii/core.py", line 1154, in read
    self.lines = self.inputter.get_lines(table)
  File "/usr/local/lib/python3.7/site-packages/astropy/io/ascii/core.py", line 303, in get_lines
    encoding=self.encoding) as fileobj:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/astropy/utils/data.py", line 193, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: ''
```

</details>

##### Steps to reproduce
```python
import stsynphot as STS
bp = STS.band('galex,fuv')
```

**Comment by pllim** [comment]
Did you grab the data files as per instructions at https://stsynphot.readthedocs.io/en/latest/#installation-and-setup ?

**Comment by pllim** [comment]
Hi, is this still a problem?

**Comment by pllim** [comment]
I have not heard back and I cannot reproduce this, so I am closing this.
